inputs:
  env:
    description: Target environment
    required: false
    default: DEV

  base_url:
    description: Base URL of the tested application
    required: false
    default: http://localhost

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Download Allure results
      uses: actions/download-artifact@v7
      with:
        name: allure-results
        path: allure-results

    - name: Add Allure metadata
      if: always()
      shell: bash
      run: |
        echo "Adding Allure executor.json"
        cat > allure-results/executor.json << EOF
        {
          "name": "GitHub Actions",
          "type": "github",
          "buildOrder": "${{ github.run_number }}",
          "buildName": "Run #${{ github.run_number }}",
          "buildUrl": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
          "reportUrl": "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
        }
        EOF

        echo "Adding Allure environment.properties"
        cat > allure-results/environment.properties << EOF
        ENV=${{ inputs.env || 'DEV' }}
        BRANCH=${{ github.ref_name }}
        BASE_URL=${{ vars.BASE_URL || 'http://localhost' }}
        COMMIT=${{ github.event.pull_request.title || github.event.head_commit.message || 'manual run' }}
        TRIGGERED_BY=${{ github.actor }}
        EOF

    - name: Get Allure history
      uses: actions/checkout@v6
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure Report action
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: 7

    - name: Deploy report to Github Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
        keep_files: false
