name: Deploy microservices-demo app
description: Deploy microservices-demo application using docker compose

inputs:
  health_check_url:
    description: The URL to check service readiness
    required: true

runs:
  using: composite

  steps:
    - name: Checkout microservices-demo
      uses: actions/checkout@v6
      with:
        repository: Valerii-Synenko/microservices-demo
        path: microservices-demo

    - name: Up and run microservices-demo app
      shell: bash
      run: |
        cd microservices-demo/deploy/docker-compose
        docker compose up -d

        echo "⏳ Waiting for containers to initialize (10s)..."
        sleep 10

        CONTAINER_COUNT=$(docker ps -q | wc -l)
        if [ "$CONTAINER_COUNT" -gt 0 ]; then
          echo "✅ $CONTAINER_COUNT containers running"
          docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" --no-trunc
        else
          echo "❌ No containers running"
          exit 1
        fi

        echo "⏳ Waiting for edge-router to accept connections..."

        for i in {1..30}; do
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" --connect-timeout 2 ${{ inputs.health_check_url }}:80 || true)

          if [ "$STATUS" = "200" ]; then
            echo "✅ edge-router is ready!"
            break
          fi

          echo "Attempt $i/30: edge-router not ready (status=$STATUS)"
          sleep 5
        done

        if [ "$STATUS" != "200" ]; then
          echo "❌ edge-router did not become ready"
          echo "Container status:"
          docker ps
          echo "edge-router logs:"
          docker logs edge-router --tail=50
          exit 1
        fi

        echo "⏳ Stabilizing services (30s)..."
        sleep 30
        echo "✅ All services ready!"
