name: set-up-poetry
description: Set up poetry. (Install + Cache + Install Dependencies)

runs:
  using: composite
  steps:
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Cache Poetry dependencies
      uses: actions/cache@v5
      with:
        path: .venv
        key: venv-${{ runner.os }}-py3.13-${{ hashFiles('poetry.lock') }}

    - name: Install Poetry dependencies
      shell: bash
      run: poetry install --no-interaction --no-root
